### ISSUE TITLE
Add delete functionality

### ISSUE THREAD

**Issue by tiaaburton** [dantespe/spectacle#22]
Can only delete data from the db by sending a query to it directly. Would like a way to interact with it through the Dataset interface to be able to click a button and delete, on cascade, from the import page.

**Comment by dantespe** [comment]
This functionality was added to the backend in 41953ed9f9cd847351ccc4a230b9ee3759948c56. This has been merged into `main` and `tiareina_v0`. Reassigning to @tiaaburton to add this functionality in the frontend. Once we have that then we should be good to close this.

Please refer to the docs to see how to delete a [dataset](https://github.com/dantespe/spectacle/#delete-dataset).
