### ISSUE TITLE
`/rest/datasets` returns 400 when it should return 200

### ISSUE THREAD

**Issue by tiaaburton** [dantespe/spectacle#9]
Server is attempting to update the headers which have a 400 error code, but it returns a result and have a rejected 200 error code.

**Comment by dantespe** [comment]
Reassigning to +tiaaburton

For which endpoint is this for?

**Comment by dantespe** [comment]
This is for `/rest/datasets`

**Comment by dantespe** [comment]
This issue has been resolved and merge into main. Marking this as closed.
